import { useState } from 'react'
import { HugeiconsIcon } from '@hugeicons/react'
import { Delete02Icon } from '@hugeicons/core-free-icons'
import { ToggleSwitch } from './ToggleSwitch'

export function EditBranchModal({ branch, isOpen, onClose, onSave, onDeleteClick }) {
  const [name, setName] = useState(branch?.name || '')
  const [phone, setPhone] = useState(branch?.phone || '')
  const [address, setAddress] = useState(branch?.address || '')
  const [username, setUsername] = useState(branch?.username || '')
  const [password, setPassword] = useState(branch?.password || '')
  const [pickupOrders, setPickupOrders] = useState(branch?.pickupOrders ?? true)
  const [deliveryOrders, setDeliveryOrders] = useState(branch?.deliveryOrders ?? false)
  const [branchOpen, setBranchOpen] = useState(branch?.active ?? true)

  const code = branch?.code || ''

  if (!isOpen || !branch) return null

  const handleSave = (e) => {
    e?.preventDefault()
    if (!name.trim()) return

    onSave({
      ...branch,
      name: name.trim(),
      phone: phone.trim(),
      address: address.trim(),
      username: username.trim(),
      password: password.trim(),
      pickupOrders,
      deliveryOrders,
      active: branchOpen,
    })
    onClose()
  }

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="edit-branch-title"
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-[1px] overflow-y-auto"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose()
      }}
    >
      <div className="flex w-full max-w-[540px] flex-col gap-6 rounded-[20px] bg-white p-8 shadow-[0px_10px_20px_rgba(0,0,0,0.16)] max-h-[92vh] overflow-y-auto my-auto">
        <h2 id="edit-branch-title" className="text-lg font-semibold text-ink">
          Edit Branch
        </h2>

        {/* Inputs Group */}
        <div className="flex flex-col gap-2.5">
          {/* Branch Name */}
          <label className="flex flex-col justify-center rounded-[10px] border border-[#e8e8e8] bg-white px-3 pt-2.5 pb-3 transition-colors focus-within:border-brand">
            <span className="text-xs font-medium text-muted">Branch Name</span>
            <input
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full text-base font-normal text-ink outline-none"
              required
            />
          </label>

          {/* Code & Phone Row */}
          <div className="flex gap-2.5">
            <div className="flex flex-1 flex-col justify-center rounded-[10px] border border-[#dcdcdc] bg-[#f5f5f5] px-3 pt-2.5 pb-3">
              <span className="text-xs font-medium text-muted">Branch Code</span>
              <span className="w-full text-base font-normal text-ink select-none">{code}</span>
            </div>

            <label className="flex flex-1 flex-col justify-center rounded-[10px] border border-[#e8e8e8] bg-white px-3 pt-2.5 pb-3 transition-colors focus-within:border-brand">
              <span className="text-xs font-medium text-muted">Phone</span>
              <input
                type="tel"
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                className="w-full text-base font-normal text-ink outline-none"
              />
            </label>
          </div>

          {/* Address */}
          <label className="flex flex-col justify-center rounded-[10px] border border-[#e8e8e8] bg-white px-3 pt-2.5 pb-3 transition-colors focus-within:border-brand">
            <span className="text-xs font-medium text-muted">Address</span>
            <input
              type="text"
              value={address}
              onChange={(e) => setAddress(e.target.value)}
              className="w-full text-base font-normal text-ink outline-none"
            />
          </label>
        </div>

        {/* Divider */}
        <div className="h-px w-full bg-[#f0ece9]" />

        {/* Employee Access */}
        <div className="flex flex-col gap-4">
          <div className="flex flex-col gap-0.5">
            <p className="text-sm font-semibold text-ink">Employee Access</p>
            <p className="text-xs text-muted">
              These credentials are used by branch staff to log into the Employee Portal. Auto-generated by default
            </p>
          </div>

          <div className="flex gap-2.5">
            <label className="flex flex-1 flex-col justify-center rounded-[10px] border border-[#e8e8e8] bg-white px-3 pt-2.5 pb-3 transition-colors focus-within:border-brand">
              <span className="text-xs font-medium text-muted">Username</span>
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full text-base font-normal text-ink outline-none"
              />
            </label>

            <label className="flex flex-1 flex-col justify-center rounded-[10px] border border-[#e8e8e8] bg-white px-3 pt-2.5 pb-3 transition-colors focus-within:border-brand">
              <span className="text-xs font-medium text-muted">Password</span>
              <input
                type="text"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full text-base font-normal text-ink outline-none"
              />
            </label>
          </div>
        </div>

        {/* Divider */}
        <div className="h-px w-full bg-[#f0ece9]" />

        {/* Toggles */}
        <div className="flex flex-col gap-4">
          {/* Pickup Orders */}
          <div className="flex items-center justify-between">
            <div className="flex flex-col">
              <span className="text-sm font-semibold text-ink">Pickup Orders</span>
              <span className="text-xs text-muted">Allow customers to place pickup orders at this branch</span>
            </div>
            <ToggleSwitch
              checked={pickupOrders}
              onChange={setPickupOrders}
              ariaLabel="Allow pickup orders"
            />
          </div>

          {/* Delivery Orders */}
          <div className="flex items-center justify-between">
            <div className="flex flex-col">
              <span className="text-sm font-semibold text-ink">Delivery Orders</span>
              <span className="text-xs text-muted">Allow customers to request delivery from this branch</span>
            </div>
            <ToggleSwitch
              checked={deliveryOrders}
              onChange={setDeliveryOrders}
              ariaLabel="Allow delivery orders"
            />
          </div>

          {/* Branch Open */}
          <div className="flex items-center justify-between">
            <div className="flex flex-col">
              <span className="text-sm font-semibold text-ink">Branch Open</span>
              <span className="text-xs text-muted">When off, this branch won't accept any new orders</span>
            </div>
            <ToggleSwitch
              checked={branchOpen}
              onChange={setBranchOpen}
              ariaLabel="Branch open status"
            />
          </div>
        </div>

        {/* Danger Zone */}
        <div className="flex flex-col gap-2 rounded-[10px] bg-[#ffecec] p-3.5 shadow-[0px_4px_10px_rgba(0,0,0,0.02)]">
          <p className="text-xs font-semibold uppercase text-[#ea0101]">Danger Zone</p>
          <p className="text-sm text-ink leading-snug">
            Permanently remove this branch and its configuration. Orders associated with it will not be deleted.
          </p>
          <button
            type="button"
            onClick={() => onDeleteClick(branch)}
            className="flex items-center gap-1.5 rounded-md bg-[#ea0101] px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-[#d00101] w-fit cursor-pointer mt-1"
          >
            <HugeiconsIcon icon={Delete02Icon} size={18} color="currentColor" />
            <span>Delete Branch</span>
          </button>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-end gap-3 pt-2">
          <button
            type="button"
            onClick={onClose}
            className="rounded-full border border-[#e8e8e8] bg-white px-6 py-3 text-sm font-semibold text-ink transition-colors hover:bg-[#f5f5f5] cursor-pointer"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleSave}
            disabled={!name.trim()}
            className="rounded-full bg-brand px-6 py-3 text-sm font-semibold text-white transition-opacity hover:opacity-90 disabled:opacity-50 cursor-pointer"
          >
            Save Changes
          </button>
        </div>
      </div>
    </div>
  )
}
