export const INITIAL_ORDERS = [
  {
    id: '#2493',
    customer: 'Sarah Jenkins',
    phone: '+1 (555) 321-9876',
    address: '415 Sourdough Lane, Apt 3B, Austin TX',
    branch: 'Downtown Main Branch',
    type: 'Delivery',
    date: '9/17/2026 10:00 AM',
    timeReceived: '10:14 AM',
    total: 22.50,
    payment: 'Card',
    status: 'Preparing', // Preparing | Ready | En Route | Delivered | Cancelled
    itemsSummary: '2x Sourdough, 1x Croissant...',
    items: [
      { name: 'Artisanal Sourdough Loaf', qty: 2, price: 6.00, total: 12.00 },
      { name: 'Flaky Butter Croissant', qty: 1, price: 2.50, total: 2.50 },
      { name: 'Vanilla Bean Pastry Cup', qty: 1, price: 4.00, total: 4.00 },
    ],
    subtotal: 18.50,
    deliveryFee: 2.50,
    tax: 1.50,
    timeline: {
      received: '10:14 AM',
      preparing: '10:13 AM',
      ready: null,
      dispatch: null,
      delivered: null,
    },
  },
  {
    id: '#2492',
    customer: 'David Miller',
    phone: '+1 (555) 432-8765',
    address: '12 Bakery Ave, Austin TX',
    branch: 'West End Branch',
    type: 'Pickup',
    date: '9/17/2026 10:00 AM',
    timeReceived: '10:12 AM',
    total: 12.98,
    payment: 'Cash',
    status: 'Ready',
    itemsSummary: '1x Chocolate Cake, 1x Latte...',
    items: [
      { name: 'Rich Chocolate Cake Slice', qty: 1, price: 8.50, total: 8.50 },
      { name: 'Iced Vanilla Latte', qty: 1, price: 4.48, total: 4.48 },
    ],
    subtotal: 12.98,
    deliveryFee: 0.00,
    tax: 0.00,
    timeline: {
      received: '10:12 AM',
      preparing: '10:15 AM',
      ready: '10:20 AM',
      dispatch: null,
      delivered: null,
    },
  },
  {
    id: '#2488',
    customer: 'Rachel Green',
    phone: '+1 (555) 987-6543',
    address: '90 Bedford St, Apt 20, New York NY',
    branch: 'Downtown Main Branch',
    type: 'Delivery',
    date: '9/17/2026 10:00 AM',
    timeReceived: '10:10 AM',
    total: 34.12,
    payment: 'Card',
    status: 'Preparing',
    itemsSummary: '3x Blueberry Scone, 2x Macchiato...',
    items: [
      { name: 'Fresh Blueberry Scone', qty: 3, price: 6.00, total: 18.00 },
      { name: 'Caramel Macchiato', qty: 2, price: 6.00, total: 12.00 },
      { name: 'Butter Shortbread Cookie', qty: 1, price: 4.12, total: 4.12 },
    ],
    subtotal: 30.12,
    deliveryFee: 2.50,
    tax: 1.50,
    timeline: {
      received: '10:10 AM',
      preparing: '10:12 AM',
      ready: null,
      dispatch: null,
      delivered: null,
    },
  },
  {
    id: '#2487',
    customer: 'Chandler Bing',
    phone: '+1 (555) 123-4567',
    address: '90 Bedford St, Apt 19, New York NY',
    branch: 'Downtown Main Branch',
    type: 'Delivery',
    date: '9/17/2026 10:00 AM',
    timeReceived: '10:08 AM',
    total: 14.50,
    payment: 'Card',
    status: 'Preparing',
    itemsSummary: '1x White Loaf, 1x Apple Danish...',
    items: [
      { name: 'Country White Loaf', qty: 1, price: 6.50, total: 6.50 },
      { name: 'Cinnamon Apple Danish', qty: 1, price: 8.00, total: 8.00 },
    ],
    subtotal: 14.50,
    deliveryFee: 0.00,
    tax: 0.00,
    timeline: {
      received: '10:08 AM',
      preparing: '10:11 AM',
      ready: null,
      dispatch: null,
      delivered: null,
    },
  },
  {
    id: '#2486',
    customer: 'Monica Geller',
    phone: '+1 (555) 234-5678',
    address: '90 Bedford St, Apt 20, New York NY',
    branch: 'West End Branch',
    type: 'Delivery',
    date: '9/17/2026 10:00 AM',
    timeReceived: '10:05 AM',
    total: 12.75,
    payment: 'Cash',
    status: 'Ready',
    itemsSummary: '2x Blueberry Muffin, 1x Black Coffee...',
    items: [
      { name: 'Jumbo Blueberry Muffin', qty: 2, price: 4.25, total: 8.50 },
      { name: 'Drip Black Coffee', qty: 1, price: 4.25, total: 4.25 },
    ],
    subtotal: 10.75,
    deliveryFee: 2.00,
    tax: 0.00,
    timeline: {
      received: '10:05 AM',
      preparing: '10:08 AM',
      ready: '10:18 AM',
      dispatch: null,
      delivered: null,
    },
  },
  {
    id: '#2489',
    customer: 'Ross Geller',
    phone: '+1 (555) 345-6789',
    address: 'Central Perk Lane, Apt 4A, New York NY',
    branch: 'Downtown Main Branch',
    type: 'Delivery',
    date: '9/17/2026 10:00 AM',
    timeReceived: '9:58 AM',
    total: 9.00,
    payment: 'Card',
    status: 'En Route',
    itemsSummary: '1x Croissant, 2x Green Tea...',
    items: [
      { name: 'Classic Butter Croissant', qty: 1, price: 5.50, total: 5.50 },
      { name: 'Organic Green Tea', qty: 2, price: 1.75, total: 3.50 },
    ],
    subtotal: 7.00,
    deliveryFee: 2.00,
    tax: 0.00,
    timeline: {
      received: '09:58 AM',
      preparing: '10:02 AM',
      ready: '10:14 AM',
      dispatch: '10:20 AM',
      delivered: null,
    },
  },
  {
    id: '#2490',
    customer: 'Phoebe Buffay',
    phone: '+1 (555) 456-7890',
    address: '5 Morton St, New York NY',
    branch: 'Downtown Main Branch',
    type: 'Pickup',
    date: '9/17/2026 10:00 AM',
    timeReceived: '9:55 AM',
    total: 10.25,
    payment: 'Card',
    status: 'Preparing',
    itemsSummary: '1x Spinach Quiche, 1x Herbal Tea...',
    items: [
      { name: 'Warm Spinach Quiche', qty: 1, price: 7.00, total: 7.00 },
      { name: 'Chamomile Herbal Tea', qty: 1, price: 3.25, total: 3.25 },
    ],
    subtotal: 10.25,
    deliveryFee: 0.00,
    tax: 0.00,
    timeline: {
      received: '09:55 AM',
      preparing: '09:59 AM',
      ready: null,
      dispatch: null,
      delivered: null,
    },
  },
  {
    id: '#2491',
    customer: 'Joey Tribbiani',
    phone: '+1 (555) 567-8901',
    address: '90 Bedford St, Apt 19, New York NY',
    branch: 'Downtown Main Branch',
    type: 'Delivery',
    date: '9/17/2026 10:00 AM',
    timeReceived: '9:50 AM',
    total: 22.00,
    payment: 'Card',
    status: 'Ready',
    itemsSummary: '3x Cheese Pizza, 1x Soda...',
    items: [
      { name: 'Artisan Cheese Pizza Slice', qty: 3, price: 6.00, total: 18.00 },
      { name: 'Italian Sparkling Soda', qty: 1, price: 4.00, total: 4.00 },
    ],
    subtotal: 19.50,
    deliveryFee: 2.50,
    tax: 0.00,
    timeline: {
      received: '09:50 AM',
      preparing: '09:54 AM',
      ready: '10:06 AM',
      dispatch: null,
      delivered: null,
    },
  },
  // Additional orders for Active tab (total 12 active)
  {
    id: '#2485',
    customer: 'Gunther Central',
    phone: '+1 (555) 678-9012',
    address: '199 Lafayette St, New York NY',
    branch: 'West End Branch',
    type: 'Pickup',
    date: '9/17/2026 9:45 AM',
    timeReceived: '9:45 AM',
    total: 16.50,
    payment: 'Cash',
    status: 'Ready',
    itemsSummary: '2x Cinnamon Roll, 1x Espresso...',
    items: [
      { name: 'Glazed Cinnamon Roll', qty: 2, price: 6.00, total: 12.00 },
      { name: 'Double Espresso', qty: 1, price: 4.50, total: 4.50 },
    ],
    subtotal: 16.50,
    deliveryFee: 0.00,
    tax: 0.00,
    timeline: {
      received: '09:45 AM',
      preparing: '09:48 AM',
      ready: '09:58 AM',
      dispatch: null,
      delivered: null,
    },
  },
  {
    id: '#2484',
    customer: 'Janice Hosenstein',
    phone: '+1 (555) 789-0123',
    address: '45 Gramercy Park S, New York NY',
    branch: 'Downtown Main Branch',
    type: 'Delivery',
    date: '9/17/2026 9:40 AM',
    timeReceived: '9:40 AM',
    total: 28.50,
    payment: 'Card',
    status: 'En Route',
    itemsSummary: '1x Strawberry Tart, 2x Cappuccino...',
    items: [
      { name: 'Glazed Strawberry Tart', qty: 1, price: 16.50, total: 16.50 },
      { name: 'Oat Milk Cappuccino', qty: 2, price: 6.00, total: 12.00 },
    ],
    subtotal: 26.00,
    deliveryFee: 2.50,
    tax: 0.00,
    timeline: {
      received: '09:40 AM',
      preparing: '09:44 AM',
      ready: '09:56 AM',
      dispatch: '10:04 AM',
      delivered: null,
    },
  },
  {
    id: '#2483',
    customer: 'Mike Hannigan',
    phone: '+1 (555) 890-1234',
    address: '88 Franklin St, New York NY',
    branch: 'Downtown Main Branch',
    type: 'Delivery',
    date: '9/17/2026 9:35 AM',
    timeReceived: '9:35 AM',
    total: 18.25,
    payment: 'Card',
    status: 'Preparing',
    itemsSummary: '1x Almond Croissant, 1x Cold Brew...',
    items: [
      { name: 'Almond Frangipane Croissant', qty: 1, price: 12.00, total: 12.00 },
      { name: 'Nitro Cold Brew', qty: 1, price: 6.25, total: 6.25 },
    ],
    subtotal: 15.75,
    deliveryFee: 2.50,
    tax: 0.00,
    timeline: {
      received: '09:35 AM',
      preparing: '09:39 AM',
      ready: null,
      dispatch: null,
      delivered: null,
    },
  },
  {
    id: '#2482',
    customer: 'Jack Geller',
    phone: '+1 (555) 901-2345',
    address: '10 Long Island Ave, Long Island NY',
    branch: 'Downtown Main Branch',
    type: 'Pickup',
    date: '9/17/2026 9:30 AM',
    timeReceived: '9:30 AM',
    total: 21.00,
    payment: 'Card',
    status: 'Preparing',
    itemsSummary: '3x Pretzel Bun, 1x Herbal Tea...',
    items: [
      { name: 'Bavarian Pretzel Bun', qty: 3, price: 5.00, total: 15.00 },
      { name: 'Iced Peach Herbal Tea', qty: 1, price: 6.00, total: 6.00 },
    ],
    subtotal: 21.00,
    deliveryFee: 0.00,
    tax: 0.00,
    timeline: {
      received: '09:30 AM',
      preparing: '09:35 AM',
      ready: null,
      dispatch: null,
      delivered: null,
    },
  },
  // Completed Orders (12 completed)
  {
    id: '#2481',
    customer: 'Judy Geller',
    phone: '+1 (555) 012-3456',
    address: '10 Long Island Ave, Long Island NY',
    branch: 'Downtown Main Branch',
    type: 'Delivery',
    date: '9/17/2026 9:15 AM',
    timeReceived: '9:15 AM',
    total: 36.40,
    payment: 'Card',
    status: 'Delivered',
    itemsSummary: '1x Celebration Cake, 2x Tea...',
    items: [
      { name: 'Vanilla Celebration Cake', qty: 1, price: 28.00, total: 28.00 },
      { name: 'English Breakfast Tea', qty: 2, price: 4.20, total: 8.40 },
    ],
    subtotal: 33.90,
    deliveryFee: 2.50,
    tax: 0.00,
    timeline: {
      received: '09:15 AM',
      preparing: '09:18 AM',
      ready: '09:32 AM',
      dispatch: '09:40 AM',
      delivered: '10:02 AM',
    },
  },
  {
    id: '#2480',
    customer: 'Carol Willick',
    phone: '+1 (555) 123-7890',
    address: '32 Columbus Ave, New York NY',
    branch: 'West End Branch',
    type: 'Pickup',
    date: '9/17/2026 9:10 AM',
    timeReceived: '9:10 AM',
    total: 15.00,
    payment: 'Card',
    status: 'Delivered',
    itemsSummary: '2x Croissant, 1x Latte...',
    items: [
      { name: 'Flaky Butter Croissant', qty: 2, price: 5.00, total: 10.00 },
      { name: 'Caffe Latte', qty: 1, price: 5.00, total: 5.00 },
    ],
    subtotal: 15.00,
    deliveryFee: 0.00,
    tax: 0.00,
    timeline: {
      received: '09:10 AM',
      preparing: '09:13 AM',
      ready: '09:22 AM',
      dispatch: null,
      delivered: '09:30 AM',
    },
  },
  {
    id: '#2479',
    customer: 'Susan Bunch',
    phone: '+1 (555) 234-8901',
    address: '32 Columbus Ave, New York NY',
    branch: 'Downtown Main Branch',
    type: 'Delivery',
    date: '9/17/2026 9:05 AM',
    timeReceived: '9:05 AM',
    total: 24.80,
    payment: 'Cash',
    status: 'Delivered',
    itemsSummary: '2x Chocolate Cruffin, 2x Mocha...',
    items: [
      { name: 'Dark Chocolate Cruffin', qty: 2, price: 6.40, total: 12.80 },
      { name: 'Iced Cafe Mocha', qty: 2, price: 6.00, total: 12.00 },
    ],
    subtotal: 22.30,
    deliveryFee: 2.50,
    tax: 0.00,
    timeline: {
      received: '09:05 AM',
      preparing: '09:09 AM',
      ready: '09:25 AM',
      dispatch: '09:32 AM',
      delivered: '09:55 AM',
    },
  },
  // Cancelled Orders (2 cancelled)
  {
    id: '#2478',
    customer: 'Ursula Buffay',
    phone: '+1 (555) 345-9012',
    address: '14 Soho Sq, New York NY',
    branch: 'Downtown Main Branch',
    type: 'Delivery',
    date: '9/17/2026 8:50 AM',
    timeReceived: '8:50 AM',
    total: 19.50,
    payment: 'Card',
    status: 'Cancelled',
    itemsSummary: '1x Matcha Cruffin, 1x Tea...',
    items: [
      { name: 'Matcha Cream Cruffin', qty: 1, price: 14.50, total: 14.50 },
      { name: 'Chai Latte', qty: 1, price: 5.00, total: 5.00 },
    ],
    subtotal: 17.00,
    deliveryFee: 2.50,
    tax: 0.00,
    timeline: {
      received: '08:50 AM',
      preparing: null,
      ready: null,
      dispatch: null,
      delivered: null,
    },
  },
  {
    id: '#2477',
    customer: 'Richard Burke',
    phone: '+1 (555) 456-0123',
    address: '77 Park Ave, New York NY',
    branch: 'West End Branch',
    type: 'Pickup',
    date: '9/17/2026 8:30 AM',
    timeReceived: '8:30 AM',
    total: 42.00,
    payment: 'Card',
    status: 'Cancelled',
    itemsSummary: '3x Bagel with Cream Cheese, 3x Coffee...',
    items: [
      { name: 'Artisan Bagel & Shmear', qty: 3, price: 8.00, total: 24.00 },
      { name: 'House Blend Roast', qty: 3, price: 6.00, total: 18.00 },
    ],
    subtotal: 42.00,
    deliveryFee: 0.00,
    tax: 0.00,
    timeline: {
      received: '08:30 AM',
      preparing: null,
      ready: null,
      dispatch: null,
      delivered: null,
    },
  },
]
